-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.exam
(
    id bigserial NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    duration_minutes integer,
    published boolean NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    creator_id bigint,
    CONSTRAINT exam_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exam_questions
(
    exam_id bigint NOT NULL,
    question_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.question
(
    id bigserial NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    correct_answer character varying(255) COLLATE pg_catalog."default",
    difficulty character varying(255) COLLATE pg_catalog."default",
    subject character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT question_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.question_options
(
    question_id bigint NOT NULL,
    options character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.result
(
    id bigserial NOT NULL,
    score integer,
    submission_date timestamp(6) without time zone,
    total_questions integer,
    exam_id bigint,
    student_id bigint,
    recording_path character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT result_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.result_selected_answers
(
    result_id bigint NOT NULL,
    selected_answers character varying(255) COLLATE pg_catalog."default",
    selected_answers_key bigint NOT NULL,
    CONSTRAINT result_selected_answers_pkey PRIMARY KEY (result_id, selected_answers_key)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username)
);

ALTER TABLE IF EXISTS public.exam
    ADD CONSTRAINT fk40vnsnl0aubrqbky6ffeu5wd9 FOREIGN KEY (creator_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exam_questions
    ADD CONSTRAINT fk4choqefx183qopsef3ajgg9fm FOREIGN KEY (exam_id)
    REFERENCES public.exam (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exam_questions
    ADD CONSTRAINT fkcygwt0t9wg31plvq2jlwvm4i FOREIGN KEY (question_id)
    REFERENCES public.question (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.question_options
    ADD CONSTRAINT fkjk4v42xhyfv4ca1yyhorsg5tv FOREIGN KEY (question_id)
    REFERENCES public.question (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.result
    ADD CONSTRAINT fk7sc8ejc10fh429vn3gfpkhem9 FOREIGN KEY (exam_id)
    REFERENCES public.exam (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.result
    ADD CONSTRAINT fkg4mvkk2n1vsrbkw4vdhu1ir5a FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.result_selected_answers
    ADD CONSTRAINT fkcgmjg94awcarqdbi8q8qg54dw FOREIGN KEY (result_id)
    REFERENCES public.result (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;